const fs = require('fs');
let c = fs.readFileSync('src/pages/Admin.tsx', 'utf8');

if (!c.includes('import { fetchApi }')) {
    c = c.replace(/import \{ useState \} from 'react';/, "import { useState, useEffect } from 'react';\nimport { fetchApi } from '../api/client';");
}

c = c.replace(/const \[catalog, setCatalog\] = useState\(initialProducts\);/, "const [catalog, setCatalog] = useState<any[]>([]);\n  useEffect(() => {\n    fetchApi('/models').then((data: any) => {\n      if (Array.isArray(data)) {\n        const formatted = data.map((m: any) => ({\n          id: m.id.toString(),\n          name: m.name,\n          category: m.category,\n          types: m.types || [],\n          scales: m.scales || ['1:10'],\n          materials: m.materials || ['PLA'],\n          basePrice: m.basePrice,\n          finishOptions: [],\n          image: m.imageUrl || 'https://placehold.co/600x700/1F2937/F97316?text=Figure',\n          printTimeH: m.printTimeH || 0,\n          filamentG: m.filamentG || 0,\n          active: m.active\n        }));\n        setCatalog(formatted);\n      }\n    }).catch(console.error);\n\n    fetchApi('/orders').then((data: any) => {\n      if (Array.isArray(data)) setOrders(data);\n    }).catch(console.error);\n\n    fetchApi('/admin/filaments').then((data: any) => {\n      if (Array.isArray(data)) setFilamentos(data);\n    }).catch(console.error);\n  }, []);");

c = c.replace(/function addProduct\(p: Partial<Product>\) \{[\s\S]*?setCatalog\(prev => \[p as Product, \.\.\.prev\]\);\n  \}/, "async function addProduct(p: Partial<Product>) {\n    const isEdit = !p.id?.startsWith('p');\n    const payload = {\n      name: p.name,\n      category: p.category,\n      types: p.types,\n      scales: p.scales,\n      materials: p.materials,\n      basePrice: p.basePrice,\n      imageUrl: p.image,\n      printTimeH: p.printTimeH,\n      filamentG: p.filamentG,\n      active: p.active\n    };\n    try {\n      if (isEdit) {\n        await fetchApi('/models/' + p.id, { method: 'PUT', body: JSON.stringify(payload) });\n        setCatalog(prev => prev.map(x => x.id === p.id ? { ...x, ...p } as Product : x));\n      } else {\n        const created: any = await fetchApi('/models', { method: 'POST', body: JSON.stringify(payload) });\n        setCatalog(prev => [{ ...p, id: created.id.toString() } as Product, ...prev]);\n      }\n    } catch (err) {\n      console.error('Erro', err);\n      alert('Erro ao salvar no banco!');\n    }\n  }");

c = c.replace(/active: initialData \? initialData\.active : true,\n  \}\);/, "active: initialData ? initialData.active : true,\n    imageFile: null as File | null,\n  });\n  const [isUploading, setIsUploading] = useState(false);");
c = c.replace(/<button type="submit" className="([^"]+)">{\(initialData \? 'Editar Produto' : 'Nova Figure \/ Produto'\)}<\/button>/, "<button disabled={isUploading} type=\"submit\" className=\" disabled:opacity-50\">{isUploading ? 'Enviando...' : (initialData ? 'Editar Produto' : 'Salvar Produto')}</button>");
c = c.replace(/onChange=\{e => setForm\(f => \(\{ \.\.\.f, image: e\.target\.value \}\)\)\}/, "onChange={e => { if (e.target.files?.[0]) { const file = e.target.files[0]; setForm(f => ({ ...f, image: URL.createObjectURL(file), imageFile: file })) } }}");
c = c.replace(/function handleSave\(e: React\.FormEvent\) \{/, "async function handleSave(e: React.FormEvent) {");
c = c.replace(/e\.preventDefault\(\);\n    onSave\(\{/, "e.preventDefault();\n    if ((form as any).imageFile) {\n      setIsUploading(true);\n      const fd = new FormData();\n      fd.append('file', (form as any).imageFile);\n      fd.append('upload_preset', 'forja_preset');\n      try {\n        const r = await fetch('https://api.cloudinary.com/v1_1/hsxlmx8k/image/upload', { method: 'POST', body: fd });\n        const d = await r.json();\n        if (d.secure_url) form.image = d.secure_url;\n      } catch (err) {\n        console.error(err);\n        alert('Erro ao enviar imagem. Verifique se o preset forja_preset está como Unsigned.');\n      } finally {\n        setIsUploading(false);\n      }\n    }\n    onSave({");
c = c.replace(/onClick=\{async \(\) => setCatalog\(prev => prev\.filter\(x => x\.id !== p\.id\)\)\}/, "onClick={async () => {\n  if(confirm('Certeza que deseja deletar?')) {\n    try {\n      await fetchApi(/models/, { method: 'DELETE' });\n      setCatalog(prev => prev.filter(x => x.id !== p.id));\n    } catch(e) {\n      alert('Erro ao deletar!');\n    }\n  }\n}}");

fs.writeFileSync('src/pages/Admin.tsx', c, 'utf8');
